services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
        HOST: "0.0.0.0"
        DB_URL: "jdbc:mysql://host.docker.internal:3307/kzoj"
        DB_USER: "root"
        DB_PASSWORD: "kzoj_db_test"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    restart: always
    volumes:
      - kzoj_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "kzoj_db_test"
    ports:
      - "3307:3306"
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 20s
        retries: 10
volumes:
  kzoj_db: